server:
  port: 8030

spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate

  jwt:
    secret: ENC(AJv6LokZXWCLSDdDEFT1UGe19935JohjmPnbyDPFNQWa+WgVgEaBrsg3Fo8Xo8Myj3KHBd5e5Ka5pLS8nyOm2NNBdvwSAbjfBlpcZENOkyA=)

jasypt:
  encryptor:
    password: ${key}
    bean: jasyptEncryptor

ncp:
  image:
    path: ENC(cgpGXPOEF5OQWiOedlvtQxqqK2l52gSzAnT+hUuBvPL/2K/aqb2L/Dbq9hksIXDmsfCZl5CH4oRpiCrV9mS3APRc4D2SzZzC)
    type: ENC(fJ6Y6vm81GNHx7aPUO6NbOwQARlq01DMfmPejXHv/4k=)

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always